### ISSUE TITLE
2018年8月11日最新Visual Studio2017CommunityでMicrosoft Development Kitで依存関係エラー

### ISSUE THREAD

**Issue by taotaotao3** [NuGet/docs.microsoft.com-nuget.ja-jp#5]
[フィードバックをこちらに入力してください]
こんにちは。
2018年8月11日最新Visual Studio2017Communityをインストールし、Microsoft Development Kit（以下MDK）のgithubをソリューションに展開し、teleportationを実行したところ、48のエラーと依存関係警告がNugetやMDKに出ました。どうしたら解決するでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 68d87097-68a1-cdd2-edfc-93fd2366fd0a
* Version Independent ID: b7d27caf-5476-2315-f4dc-e413b1be0726
* Content: [NuGet パッケージの依存関係の解決](https://docs.microsoft.com/ja-jp/nuget/consume-packages/dependency-resolution)
* Content Source: [docs/consume-packages/Dependency-Resolution.md](https://github.com/NuGet/docs.microsoft.com-nuget.ja-jp/blob/live/docs/consume-packages/Dependency-Resolution.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by LisandroSu** [comment]
こんにちは、@taotaotao3

ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 

ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 

ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 

記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 
Microsoft DOCS International Team
